# docker stack ps WORDPRESS
# docker stack deploy --compose-file wordpress.yml --with-registry-auth wordpress
#
# docker container ls
# docker service logs WORDPRESS_wordpress
# docker service ps --no-trunc WORDPRESS_mysql (para ver errores de servicios que no parten)
# journalctl -u docker.service | tail -n 50 (para ver otros errores)
# docker service scale WORDPRESS_wordpress=1
#
#

version: '3.7'
services:
  ###
  ### wordpress
  wordpress:
    image: wordpress:php7.2-fpm
    restart: always    
    ports:
      - 8081:9000
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: geoportal
      WORDPRESS_DB_PASSWORD: portalgeo
      WORDPRESS_DB_NAME: wordressdb
    volumes:
      - type: bind
        source: /var/geoportal/wordpress/html
        target: /var/www/html
  ##
  ## mysql (usada por wordpress)
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordressdb
      MYSQL_USER: geoportal
      MYSQL_PASSWORD: portalgeo
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - type: bind
        source: /var/geoportal/mysql
        target: /var/lib/mysql
          